- hosts: all
  gather_facts: False
  become: True

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: copy the nginx config file and restart nginx
      copy:
        src: files/e03.cfg
        dest: /etc/nginx/sites-available/e03.cfg
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/e03.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: restart nginx
      service:
        name: nginx
        state: restarted

